//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblMusteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMusteri()
        {
            this.tblSatis = new HashSet<tblSatis>();
        }
    
        public int musteriId { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz !")]
        [StringLength(50, ErrorMessage = "Maksimum 50 karakter uzunluðunda olabilir !")]  
        public string musteriAd { get; set; }

        [StringLength(50, ErrorMessage = "Maksimum 50 karakter uzunluðunda olabilir !")]
        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz !")]
        public string musteriSoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSatis> tblSatis { get; set; }
    }
}
